name: Download and Replace XML
on:
  schedule:
      - cron: "*/30 * * * *"
  push:
    branches:
      - main

jobs:
  download_replace:
    permissions:
     actions: write
     checks: write
     contents: write
     deployments: write
     issues: write
     packages: write
     pull-requests: write
     repository-projects: write
     security-events: write
     statuses: write
    runs-on: ubuntu-latest

    steps:
    - name: Remove Directory
      run: |
        rm -rf nitter-xml
        
    - name: Checkout code
      uses: actions/checkout@main

    - name: Clone Private Repository
      run: |
        rm -f sub.xml
          
    - name: Download XML
      run: |
        wget -O "sub.xml" "https://nitter.woodland.cafe/pj_sekai/search/rss?f=tweets&q=exclude%3Areplies+OR+to%3Apj_sekai"
      # URLと出力ファイル名をダブルクォーテーションで囲みます

    - name: Replace text
      run: |
        sed -i 's/nitter.woodland.cafe/twitter.com/g' "sub.xml"
      # ファイル名をダブルクォーテーションで囲みます

    - name: Commit and Push Changes
      run: |
        git config user.email "128672410+mikutoyuto@users.noreply.github.com"
        git config user.name "mikutoyuto"
        git add .
        git commit -m "Update XML" || echo "nothing to commit"
        git push origin main
